name: Ubuntu Client

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Protobuf
        run: sudo apt-get install protobuf-compiler

      - name: Build
        run: |
          cd client
          cargo build --verbose